### ISSUE TITLE
Extract services from this repository?

### ISSUE THREAD

**Issue by tjk** [shellphish/ictf-framework#20]
Does it go against the goals of this project to simply define an "interface" for services (which there might already be) but not provide any from within this repository (perhaps move them to `ucsb-seclab/ictf-services` and then pull them in when bootstrapping -- if desired)?

**Comment by zardus** [comment]
There's a pretty well-defined and fairly simple "interface" for services, in terms of installation, starting/stopping, and SLA checks. There isn't really anything stopping us from moving them to a separate repo, and I can see the advantage of that (i.e., having a separate repo for CTF organizers to keep their services private until a CTF starts).
