### ISSUE TITLE
iscontinued?

### ISSUE THREAD

**Issue by einar-lanfranco** [shellphish/ictf-framework#23]
Hello boys, is the project dead or you plan to make new changes?
Hints:
- We played ictf 2015 on Decemeber/15 but last commit is about a year ago.
- Box links are broken.

Thanks
Einar

**Comment by taloweb** [comment]
I'm looking for VM models too
I would like to find Organization and Teams VMs .vdi files or having any specification about creation of these VMs, any suggestion?
